import { Inter } from "next/font/google"; // You can remove this if you add the <link> below
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] }); // You can remove this line

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark"> {/* Set dark mode globally */}
      <head>
        {/* Add these two lines for the Inter font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </head>
      <body className="bg-background text-foreground font-sans">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}